import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :portfolio_project, PortfolioProjectWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: PortfolioProject.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :portfolio_project, PortfolioProjectWeb.Endpoint,
  url: [host: "danielmusau.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: [
    "//danielmusau.com",
    "//www.danielmusau.com",
    "//daniel-musau.gigalixirapp.com/"
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
